language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  file_by_file_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!**/*.lock"
    - "!package-lock.json"
    - "!yarn.lock"
    - "!pnpm-lock.yaml"
    - "!public/**"
    - "!.next/**"
    - "!node_modules/**"
chat:
  auto_reply: true
